monitored_devices = [
    "VID_046D&PID_085C",
    "VID_3142&PID_0686"
]

# Just the arguments now!
disconnect_cmds = [
#    '/SetValue "\\.\Display1\Monitor0" 60 17',
    '/SetValue "\\.\Display2\Monitor0" 60 15'
]

connect_cmds = [
#    '/SetValue "\\.\Display1\Monitor0" 60 15',
    '/SetValue "\\.\Display2\Monitor0" 60 17'
]